import { useState, useEffect, useCallback } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { loadStripe } from "@stripe/stripe-js";
import { EmbeddedCheckoutProvider, EmbeddedCheckout } from "@stripe/react-stripe-js";
import { useToast } from "@/hooks/use-toast";

interface CheckoutDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  priceId: string;
  productName: string;
}

// Memoize the Stripe promise so it's only loaded once
const stripePromise = fetch('/api/stripe-config')
  .then((res) => res.json())
  .then((data) => {
    if (data.publishableKey) {
      return loadStripe(data.publishableKey);
    }
    throw new Error('Stripe publishable key not found');
  });

export default function CheckoutDialog({ open, onOpenChange, priceId, productName }: CheckoutDialogProps) {
  const [clientSecret, setClientSecret] = useState<string | null>(null);
  const { toast } = useToast();

  const fetchClientSecret = useCallback(() => {
    // Don't fetch if it's already been fetched
    if (clientSecret) return;

    fetch('/api/create-checkout-session', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ priceId }),
    })
      .then((res) => {
        if (!res.ok) {
          return res.json().then(err => { throw new Error(err.error || 'Failed to create checkout session') });
        }
        return res.json();
      })
      .then((data) => {
        setClientSecret(data.clientSecret);
      })
      .catch((error) => {
        console.error('Error creating checkout session:', error);
        toast({
          title: "Error",
          description: error.message || "Failed to initialize checkout. Please try again.",
          variant: "destructive",
        });
        onOpenChange(false);
      });
  }, [priceId, clientSecret, onOpenChange, toast]);

  // Create checkout session only when dialog opens
  useEffect(() => {
    if (open) {
      fetchClientSecret();
    } else {
      // Clear client secret when dialog closes
      setClientSecret(null);
    }
  }, [open, fetchClientSecret]);

  const options = clientSecret ? { clientSecret } : undefined;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-3xl h-[600px] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Complete Your Purchase</DialogTitle>
          <DialogDescription>
            {productName} - Secure payment powered by Stripe
          </DialogDescription>
        </DialogHeader>

        <div className="mt-4">
          {open && clientSecret ? (
            <EmbeddedCheckoutProvider stripe={stripePromise} options={options}>
              <EmbeddedCheckout />
            </EmbeddedCheckoutProvider>
          ) : (
            <div className="flex items-center justify-center h-96">
              <div className="text-center space-y-4">
                <div className="animate-spin h-8 w-8 border-4 border-primary border-t-transparent rounded-full mx-auto"></div>
                <p className="text-sm text-muted-foreground">Loading checkout...</p>
              </div>
            </div>
          )}
        </div>

        <div className="px-6 py-3 bg-muted/30 rounded-md border border-muted mt-4">
          <p className="text-xs text-muted-foreground italic">
            <strong>AI Content Notice:</strong> All videos created on MakeMyDogTalk.com are generated by artificial intelligence.
            Results may vary and may not perfectly match your uploaded image or prompt.
            Videos are intended for entertainment purposes only.
            By using this service, you agree to receive AI-generated output that may contain imperfections, variations, or unexpected results.
          </p>
        </div>
      </DialogContent>
    </Dialog>
  );
}
